---
apiVersion: ambassador/v1
kind: Module
name: ambassador
config:
  enable_grpc_web: true
  cors:    
    origins: "*"
    methods: POST, GET, OPTIONS
    headers: "authorization,*"
    credentials: true
    exposed_headers: "authorization,*"